### ISSUE TITLE
Red apple tree page in "Wild Fruits" entry

### ISSUE THREAD

**Issue by Varnus** [TerraFirmaCraft/Field-Guide#11]
![image](https://github.com/TerraFirmaCraft/Field-Guide/assets/62480212/d8b8d8db-0f91-4e5e-87be-86b39224a8d4)
the page is referencing olive trees intead. I think the blooming phases are the same and the temperature and rainfall seem to be correct, so only the name is wrong I think

**Comment by Varnus** [comment]
It is also present in the in game field guide

**Comment by alcatrazEscapee** [comment]
This repo only hosts the infrastructure to port the field guide to web - this isn't the right location for this issue. I've noted and am tracking it in https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/2412 instead.
